name: Build and Deploy to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "simple-manager-app" # Crie esse nome no Azure antes
  ACR_NAME: "henriquerm02.azurecr.io"
  IMAGE_NAME: "simple-manager-java"
  RESOURCE_GROUP: "rg-simple-manager"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Você vai gerar isso no Azure

    - name: Login to ACR
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Build and Push Docker Image
      run: |
        docker build . -t ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: '${{ env.ACR_NAME }}/minha-app:${{ github.sha }}'